name: Main workflow
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    env:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PORT: 3307
    steps:
      - name: üîÄ Checkout
        uses: actions/checkout@v2

      # Maybe not useful since github.com/actions/virtual-environments/issues/375 ?
      # - name: üßπ Shutdown Ubuntu MySQL (SUDO)
      #   run: sudo service mysql stop

      - name: üîê Create env file
        run: |
          touch .env
          echo SECRET=$(openssl rand -base64 32) >> .env
          echo NEXTAUTH_URL=http://localhost:3000 >> .env
          echo DB_CONNECTION=mysql >> .env
          echo DB_HOST=localhost >> .env
          echo DB_USERNAME=root >> .env
          echo DB_PASSWORD=$MYSQL_ROOT_PASSWORD >> .env
          echo DB_DATABASE=iwantmymoneyback >> .env
          echo DB_PORT=$MYSQL_PORT >> .env
          echo DB_SYNCHRONIZE=true >> .env
          echo DB_LOGGING=false >> .env
          cat .env

      - name: üê¨ Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: $MYSQL_PORT
          container port: $MYSQL_PORT
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'iwantmymoneyback'
          mysql root password: $MYSQL_ROOT_PASSWORD

      - name: ‚è≤ Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=$MYSQL_ROOT_PASSWORD; do
            mysqladmin status --host=127.0.0.1 --password=$MYSQL_ROOT_PASSWORD
            sleep 1
          done
      - name: üóÉ DB creation
        run: mysql -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD iwantmymoneyback < cypress/fixtures/DbFinal.sql

      - name: üì™ Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ~/.next
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: üß∞ Install dependencies
        run: npm ci

      # - name: üì¶ Build project
      #   run: npm run build --if-present

      - name: ‚úí Run lint
        continue-on-error: true
        run: npm run lint

      - name: üêõ Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/projet-gl/*.js
          # "npm run dev" replace "npm start" for the moment bc build job fails
          start: npm run dev
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000/'
