name: Main workflow
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸ”€ Checkout
        uses: actions/checkout@v2

      - name: ğŸ§¹ Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: ğŸ” Create env file
        run: |
          touch .env
          echo SECRET=$(openssl rand -base64 32) >> .env
          echo NEXTAUTH_URL=http://localhost:3000 >> .env
          echo DB_CONNECTION=mysql >> .env
          echo DB_HOST=localhost >> .env
          echo DB_USERNAME=root >> .env
          echo DB_PASSWORD=example >> .env
          echo DB_DATABASE=iwantmymoneyback >> .env
          echo DB_PORT=3306 >> .env
          echo DB_SYNCHRONIZE=true >> .env
          echo DB_LOGGING=false >> .env
          cat .env

      # - name: ğŸ¬ Set up MySQL
      #   uses: mirromutth/mysql-action@v1.1
      #   with:
      #     host port: 3306
      #     container port: 3306
      #     character set server: 'utf8'
      #     collation server: 'utf8_general_ci'
      #     mysql version: '8.0'
      #     mysql database: 'iwantmymoneyback'
      #     mysql root password: 'example'

      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: '10.6'
          mysql database: 'iwantmymoneyback'
          mysql root password: 'example'
      #     mysql user: 'admin'
      #     mysql password: 'admin'

      # - name: ğŸ—ƒ DB creation
      #   run: mysql -h 127.0.0.1 --connect-timeout=20 -uadmin -padmin iwantmymoneyback < cypress/fixtures/DbFinal.sql

      - name: ğŸ“ª Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: ğŸ§° Install dependencies
        run: npm ci

      # - name: ğŸ“¦ Build project
      #   run: npm run build --if-present

      - name: âœ’ Run lint
        continue-on-error: true
        run: npm run lint

      - name: ğŸ› Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/projet-gl/*.js
          # "npm run dev" replace "npm start" for the moment bc build job fails
          start: npm run dev
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000/'
