name: Main workflow
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iwantmymoneyback
    steps:
      - name: ðŸ”€ Checkout
        uses: actions/checkout@v2

      - name: Start mysql service
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE $MYSQL_DATABASE;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot

      - name: ðŸ” Create env file
        run: |
          touch .env
          echo SECRET=$(openssl rand -base64 32) >> .env
          echo NEXTAUTH_URL=http://localhost:3000 >> .env
          echo DB_CONNECTION=mysql >> .env
          echo DB_HOST=localhost >> .env
          echo DB_USERNAME=root >> .env
          echo DB_PASSWORD=$MYSQL_ROOT_PASSWORD >> .env
          echo DB_DATABASE=$MYSQL_DATABASE >> .env
          echo DB_PORT=3306 >> .env
          echo DB_SYNCHRONIZE=true >> .env
          echo DB_LOGGING=false >> .env
          cat .env

      - name: ðŸ—ƒ DB creation
        run: mysql -u root --password=$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < cypress/fixtures/DbFinal.sql

      - name: ðŸ“ª Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ~/.next
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: ðŸ§° Install dependencies
        run: npm ci

      # - name: ðŸ“¦ Build project
      #   run: npm run build --if-present

      - name: âœ’ Run lint
        continue-on-error: true
        run: npm run lint

      - name: ðŸ› Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/projet-gl/*.js
          # "npm run dev" replace "npm start" for the moment bc build job fails
          start: npm run dev
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000/'
